#!/bin/bash

# Scripts in this directory will be executed by cloud-init on the first boot of VMs
# created from your image.  Things like generating passwords, configuration requiring IP address
# or other items that will be unique to each instance should be done in scripts here.

#
# Setup Bitwarden Installer
# ref: https://help.bitwarden.com/article/install-on-premise/
#

docker pull ghcr.io/bitwarden/setup

curl -L -s -o /home/bitwarden/bitwarden.sh "https://func.bitwarden.com/api/dl/?app=self-host&platform=linux"

chmod +x /home/bitwarden/bitwarden.sh
chown bitwarden:bitwarden /home/bitwarden/bitwarden.sh
