#!/bin/sh
#
# Configured as part of the Bitwarden Marketplace Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to your Bitwarden server
  https://bitwarden.com

Complete documentation:
  https://help.bitwarden.com/hosting/

Configuration:
  Configuration changes can be made in /home/bitwarden/bwdata/config.yml and
  /home/bitwarden/bwdata/env/global.override.env

Common commands:
  sudo -i -u bitwarden /home/bitwarden/bitwarden.sh stop
  sudo -i -u bitwarden /home/bitwarden/bitwarden.sh restart
  sudo -i -u bitwarden /home/bitwarden/bitwarden.sh rebuild

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
