#!/bin/bash

# Scripts in this directory will be executed by cloud-init on the first boot of servers
# created from your image.  Things like generating passwords, configuration requiring IP address
# or other items that will be unique to each instance should be done in scripts here.

# The Bitwarden edition selection and installation wizard runs on the first interactive login.
# See /etc/profile.d/bitwarden-first-login.sh
