#!/bin/bash

# Scripts in this directory will be executed by cloud-init on the first boot of servers
# created from your image.  Things like generating passwords, configuration requiring IP address
# or other items that will be unique to each instance should be done in scripts here.

# The Bitwarden edition selection and installation wizard is run on demand by
# the user via `sudo bitwarden-setup` (advertised in the message of the day).
# See /opt/bitwarden/setup-wizard.sh
