name: Release
run-name: Release ${{ inputs.release_type }} v${{ inputs.release_version }}

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release Version (example: '2025.2.1')"
        required: true
      release_type:
        description: "Release Options"
        required: true
        default: "Release"
        type: choice
        options:
          - Release
          - Dry Run

env:
  _AZ_REGISTRY: bitwardenprod.azurecr.io

permissions:
  contents: read

jobs:
  release-bitwarden-lite:
    name: Release Bitwarden Lite
    runs-on: ubuntu-24.04
    env:
      _RELEASE_VERSION: ${{ inputs.release_version }}-beta # TODO: remove `-beta` after GA
    permissions:
      id-token: write
      packages: write
    steps:
      - name: Log in to Azure
        uses: bitwarden/gh-actions/azure-login@main
        with:
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          client_id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: Push version and latest image
        if: ${{ inputs.release_type != 'Dry Run' }}
        run: |
          skopeo --version
          skopeo login "$_AZ_REGISTRY" -u 00000000-0000-0000-0000-000000000000 -p "$(az acr login --expose-token --name "${_AZ_REGISTRY%.azurecr.io}" | jq -r .accessToken)"
          skopeo copy --all "docker://$_AZ_REGISTRY/lite:beta" "docker://ghcr.io/bitwarden/lite:$_RELEASE_VERSION"
          skopeo copy --all "docker://$_AZ_REGISTRY/lite:beta" "docker://ghcr.io/bitwarden/lite:beta" # TODO: Delete after GA
          # skopeo copy --all "docker://$_AZ_REGISTRY/lite:beta" "docker://ghcr.io/bitwarden/lite:latest" # TODO: uncomment after GA

      - name: Sign image with Cosign
        run: |
          cosign sign --yes "ghcr.io/bitwarden/lite:$_RELEASE_VERSION"
          cosign sign --yes "ghcr.io/bitwarden/lite:latest"

      - name: Log out of skopeo and ghcr.io
        run: |
          skopeo logout --all
          docker logout ghcr.io

      ########## ACR PROD ##########
      - name: Login to Azure ACR
        run: az acr login -n "${_AZ_REGISTRY%.azurecr.io}"

      - name: Pull latest project image
        run: |
          if [[ "${{ inputs.release_type }}" == "Dry Run" ]]; then
            docker pull "$_AZ_REGISTRY/lite:dev"
          else
            docker pull "$_AZ_REGISTRY/lite:beta"
          fi

      - name: Tag version and latest
        run: |
          if [[ "${{ inputs.release_type }}" == "Dry Run" ]]; then
            docker tag "$_AZ_REGISTRY/lite:dev" "$_AZ_REGISTRY/lite:dryrun"
          else
            docker tag "$_AZ_REGISTRY/lite:beta" "$_AZ_REGISTRY/lite:$_RELEASE_VERSION"
            docker tag "$_AZ_REGISTRY/lite:beta" "$_AZ_REGISTRY/lite:latest"
          fi

      - name: Push version and latest image
        if: ${{ inputs.release_type != 'Dry Run' }}
        run: |
          docker push "$_AZ_REGISTRY/lite:$_RELEASE_VERSION"
          docker push "$_AZ_REGISTRY/lite:latest"

      - name: Log out of Docker
        run: docker logout "$_AZ_REGISTRY"

      - name: Log out from Azure
        uses: bitwarden/gh-actions/azure-logout@main
