name: Update Links

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release Tag"
        required: true

jobs:
  update-links:
    name: Update Links
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Azure - CI Subscription
        uses: Azure/login@e15b166166a8746d1a47596803bd8c1b595455cf # v1.6.0
        with:
          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}

      - name: Retrieve secrets
        id: retrieve-secrets
        env:
          KEYVAULT: bitwarden-ci
          SECRETS: |
            rebrandly-apikey
        run: |
          for i in ${SECRETS//,/ }
          do
            VALUE=$(az keyvault secret show --vault-name $KEYVAULT --name $i --query value --output tsv)
            echo "::add-mask::$VALUE"
            echo "$i=$VALUE" >> $GITHUB_OUTPUT
          done

      - name: Set tag name
        id: tag-name
        run: |
          if [ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]; then
            echo "value=${{ github.event.inputs.release_tag }}" >> $GITHUB_OUTPUT
          else
            echo "value=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          fi

      - name: Update Bitwarden Script PowerShell Link
        uses: bitwarden/gh-actions/update-rebrandly-link@main
        with:
          apikey: ${{ steps.retrieve-secrets.outputs.rebrandly-apikey }}
          domain: "go.btwrdn.co"
          slashtag: "bw-ps"
          destination: "https://github.com/bitwarden/self-host/releases/download/${{ steps.tag-name.outputs.value }}/bitwarden.ps1"

      - name: Update Run Script PowerShell Link
        uses: bitwarden/gh-actions/update-rebrandly-link@main
        with:
          apikey: ${{ steps.retrieve-secrets.outputs.rebrandly-apikey }}
          domain: "go.btwrdn.co"
          slashtag: "bw-ps-run"
          destination: "https://github.com/bitwarden/self-host/releases/download/${{ steps.tag-name.outputs.value }}/run.ps1"

      - name: Update Bitwarden Script Shell Link
        uses: bitwarden/gh-actions/update-rebrandly-link@main
        with:
          apikey: ${{ steps.retrieve-secrets.outputs.rebrandly-apikey }}
          domain: "go.btwrdn.co"
          slashtag: "bw-sh"
          destination: "https://github.com/bitwarden/self-host/releases/download/${{ steps.tag-name.outputs.value }}/bitwarden.sh"

      - name: Update Run Script Shell Link
        uses: bitwarden/gh-actions/update-rebrandly-link@main
        with:
          apikey: ${{ steps.retrieve-secrets.outputs.rebrandly-apikey }}
          domain: "go.btwrdn.co"
          slashtag: "bw-sh-run"
          destination: "https://github.com/bitwarden/self-host/releases/download/${{ steps.tag-name.outputs.value }}/run.sh"
